# Generated by Django 5.1.2 on 2025-04-23 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_leaveform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveform',
            old_name='user',
            new_name='username',
        ),
    ]
