# Generated by Django 5.1.2 on 2025-04-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_rename_user_leaveform_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveform',
            name='username',
        ),
        migrations.AddField(
            model_name='leaveform',
            name='name',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
